name: Android CI and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build_variant:
        description: 'Build variant to compile (e.g., Debug, Release)'
        required: true
        default: 'Release'
        type: choice
        options:
          - Release
          - Debug

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Accept Android SDK licenses
        run: |
          if [ -d "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" ]; then
            yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
          elif [ -d "$ANDROID_HOME/tools/bin" ]; then
            yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses
          elif [ -d "$ANDROID_HOME/cmdline-tools/latest/bin" ]; then
            yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
          else
            echo "Could not find sdkmanager"
            exit 1
          fi

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Generate Gradle Wrapper (if not exists)
        run: |
          if [ ! -f "./gradlew" ]; then
            echo "gradlew not found, generating wrapper..."
            gradle wrapper --gradle-version=8.2
            chmod +x ./gradlew
          else
            echo "gradlew found, making it executable..."
            chmod +x ./gradlew
          fi

      - name: Build with Gradle
        env:
          BUILD_VARIANT_INPUT: ${{ github.event.inputs.build_variant || 'Release' }}
        run: ./gradlew :app:assemble${{ env.BUILD_VARIANT_INPUT }} --no-daemon

      - name: Create Release Tag
        id: create_tag
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && github.event.inputs.build_variant == 'Release')
        run: echo "TAG_NAME=release-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && github.event.inputs.build_variant == 'Release')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: Release ${{ env.TAG_NAME }}
          draft: false
          prerelease: false

      - name: Find APK file
        id: find_apk
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && github.event.inputs.build_variant == 'Release')
        run: |
          VARIANT_LOWER=$(echo "${{ github.event.inputs.build_variant || 'release' }}" | tr '[:upper:]' '[:lower:]')
          APK_PATH=$(find ./app/build/outputs/apk -name "*.apk" -type f | head -1)
          if [ -z "$APK_PATH" ]; then
            APK_PATH="./app/build/outputs/apk/${VARIANT_LOWER}/app-${VARIANT_LOWER}.apk"
          fi
          echo "APK_PATH=$APK_PATH" >> $GITHUB_ENV
          echo "Found APK at: $APK_PATH"

      - name: Find AAB file
        id: find_aab
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && github.event.inputs.build_variant == 'Release')
        run: |
          VARIANT_LOWER=$(echo "${{ github.event.inputs.build_variant || 'release' }}" | tr '[:upper:]' '[:lower:]')
          AAB_PATH=$(find ./app/build/outputs/bundle -name "*.aab" -type f | head -1)
          if [ -z "$AAB_PATH" ]; then
            AAB_PATH="./app/build/outputs/bundle/${VARIANT_LOWER}/app-${VARIANT_LOWER}.aab"
          fi
          echo "AAB_PATH=$AAB_PATH" >> $GITHUB_ENV
          echo "Found AAB at: $AAB_PATH"

      - name: Upload Release Assets
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && github.event.inputs.build_variant == 'Release')
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          files: |
            ${{ env.APK_PATH }}
            ${{ env.AAB_PATH }}
