name: Android CI and Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build_variant:
        description: 'Build variant to compile (e.g., Debug, Release)'
        required: true
        default: 'Release'
        type: choice
        options:
          - Release
          - Debug

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Accept Android SDK licenses
        run: |
          export JAVA_OPTS="--add-modules java.xml.bind"
          if [ -d "$ANDROID_SDK_ROOT/cmdline-tools/latest/bin" ]; then
            yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
          elif [ -d "$ANDROID_HOME/tools/bin" ]; then
            yes | $ANDROID_HOME/tools/bin/sdkmanager --licenses
          else
            echo "Could not find sdkmanager"
            exit 1
          fi

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.2'

      - name: Set Build Variant (and lowercase variant)
        id: build_variant
        run: |
          VARIANT="${{ github.event.inputs.build_variant || 'Release' }}"
          echo "BUILD_VARIANT=$VARIANT" >> $GITHUB_ENV
          echo "BUILD_VARIANT_LOWER=$(echo $VARIANT | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build with Gradle
        run: gradle :app:assemble${{ env.BUILD_VARIANT }} --no-daemon

      - name: Create Release Tag
        id: create_tag
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && env.BUILD_VARIANT == 'Release')
        run: echo "TAG_NAME=release-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_ENV

      - name: Create GitHub Release
        id: create_release
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && env.BUILD_VARIANT == 'Release')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          draft: false
          prerelease: false

      - name: Upload Release Asset (APK)
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && env.BUILD_VARIANT == 'Release')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./app/build/outputs/apk/${{ env.BUILD_VARIANT_LOWER }}/app-${{ env.BUILD_VARIANT_LOWER }}.apk
          asset_name: MusicPlayer-${{ env.TAG_NAME }}-${{ env.BUILD_VARIANT_LOWER }}.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload Release Asset (AAB)
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'workflow_dispatch' && env.BUILD_VARIANT == 'Release')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./app/build/outputs/bundle/${{ env.BUILD_VARIANT_LOWER }}/app-${{ env.BUILD_VARIANT_LOWER }}.aab
          asset_name: MusicPlayer-${{ env.TAG_NAME }}-${{ env.BUILD_VARIANT_LOWER }}.aab
          asset_content_type: application/zip
